### ISSUE TITLE
内存占用优化

### ISSUE THREAD

**Issue by BTMuli** [BTMuli/Tauri.Genshin#13]
### 任务描述

本来以为sqlite相比indexedDB内存占用小，结果今天写完看了一下，成就页飚到900多M😢

@frg2089 岛风酱帮帮😭😭😭

### 预期版本

Alpha v0.1.4 or Alpha v0.1.5

### 当前提交

Alpha v0.1.4

**Comment by BTMuli** [comment]
方案一：返回数量大于30只渲染前30，滑动到底部后通过按钮或者监听加载10个元素

方案二：自己写div而非用v-list-item，减少dom渲染数量

方案三：页面只需要一次获取全部成就数据，然后后面的查看，查询通过操作这个数据进行，无需调用数据库查询

反正我都试了下，虽然感觉都有优化，但是交互效果不如之前的自然

**Comment by frg2089** [comment]
方案四：虚拟化列表

**Comment by BTMuli** [comment]
有一说一，debug的时候devtools占的内存比本体都高（）
